CREATE TABLE IF NOT EXISTS  USER (
   ID           BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
   FIRST_NAME   VARCHAR(50) NOT NULL,
   LAST_NAME    VARCHAR(50) NOT NULL,
   PASSPORT_NUMBER          INT,
   CLIENT_TYPE  VARCHAR(10) NOT NULL DEFAULT 'NEW'
);

CREATE TABLE IF NOT EXISTS COUNTRY (
   ID           BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
   NAME         VARCHAR(50) NOT NULL,
   LANGUAG      VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS CITY (
   ID                    BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
   COUNTRY_ID               BIGINT      NOT NULL,
   NAME                  VARCHAR(50) NOT NULL,
   POPULATION INT         NOT NULL,
   DISCRIMINATOR         VARCHAR(50) NOT NULL,
  COLDEST_TEMP    INT,
   COLDEST_MONTH     VARCHAR(50),
   HOTTEST_TEMP                INT,
   HOTTEST_MONTH     VARCHAR(50),

   FOREIGN KEY (COUNTRY_ID) references COUNTRY (ID)
);

CREATE TABLE IF NOT EXISTS ORDER_TAB (
  ID                    BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
  COUNTRY_ID               BIGINT      NOT NULL,
  CITY_ID              BIGINT      NOT NULL,
  USER_ID               BIGINT      NOT NULL,
  PRICE                 INT,
  DESCRIPTION           VARCHAR(150),

 FOREIGN KEY (USER_ID) references USER (ID),
 FOREIGN KEY (COUNTRY_ID) references COUNTRY (ID),
 FOREIGN KEY (CITY_ID) references CITY (ID)
);


